### ISSUE TITLE
adding contextual help tab UI

### ISSUE THREAD

**Issue by norcross** [reaktivstudios/locomotive#102]
Would help for a cleaner overall UI, and we can add hooks, etc for devs to add on to (for things like help, descriptions, etc).

To start, I'm thinking a short intro about it and pointing to the various parts of GH (issues, wiki, etc). If y'all are on board, I'll gladly take this myself.

**Comment by jjeaton** [comment]
In support of this for the future release milestone.

**Comment by JasonHoffmann** [comment]
I can see this being useful to beta testers. Certainly not blocking, but will help smooth issues out 👍
