### ISSUE TITLE
global admin CSS declaration causing spacing issues in help tab

### ISSUE THREAD

**Issue by norcross** [reaktivstudios/locomotive#103]
the piece of CSS below is creating an issue with the contextual help tab by adding additional space in the content section.

```css
* {
	box-sizing: border-box;
}
```
**incorrect spacing**
![incorrect spacing](https://cloud.githubusercontent.com/assets/98561/22333289/632fd74e-e3a3-11e6-9bd6-1ce7167cb81b.png)

**correct spacing**
![correct spacing](https://cloud.githubusercontent.com/assets/98561/22333290/63302d7a-e3a3-11e6-872f-11dd2fea30f6.png)

Can we declare this in a way that they **_only_** apply to the actual admin UI (and any related React components)?

related #102

**Comment by JasonHoffmann** [comment]
Should be pretty easy to scope that CSS just to the batch section by changing in assets/main.css:

````
* {
  box-sizing: border-box;
}
````
to

````
#batch-main {
  box-sizing: border-box;
}
````

Also, thinking out loud, that rule in general can probably just be removed entirely. Not sure how it would effect the UI, but that seems work aroundable.

**Comment by jjeaton** [comment]
I think it would need to be:

```
#batch-main * {
  box-sizing: border-box;
}
```

**Comment by JasonHoffmann** [comment]
Yup, that's the one.

**Comment by norcross** [comment]
I can correct that in the same PR as the actual help tab
