### ISSUE TITLE
posts_per_page ignored

### ISSUE THREAD

**Issue by mdorchain** [reaktivstudios/locomotive#120]
Hi, the posts_per_page arg doesn't seem to have any effect on the initial query.
In this example, the loop keeps going instead of working on the first 10 products.

```
function delete_expired_auction_units() {
	register_batch_process( array (
		'name' => 'Delete Expired Auction Units',
		'type' => 'post',
		'callback' => 'process_delete_expired_auction_units',
		'args' => array (
			'posts_per_page' => 10,
			'post_type' => 'product',
			'post_status' => 'any',
			'meta_query' => array (
				array (
					'key' => '_auction_dates_to',
					'value' => date( "Y-m-d H:i" ),
					'compare' => '<'
				),
			)
		),
	) );
}
```

**Comment by norcross** [comment]
have you checked to see if anything else is modifying the `WP_Query` call?

**Comment by JasonHoffmann** [comment]
@mdorchain Locomotive is actually set up for batch processing, so it works by running through all of your data that matches the criteria of your query. The `posts_per_page` parameter sets how many data objects should be processed _at a time_ not how many posts will be processed _total_. If you'd only like to process a certain amount of objects, you may want to look into narrowing the results of the full query set by using a date query parameter or something else that would limit the total number of results.

**Comment by mdorchain** [comment]
Thanks @JasonHoffmann for the explanation. This explains everything.

**Comment by TylerBarnes** [comment]
The documentation is a bit confusing on this. It says
`
Next you need to define your callback function. Locomotive will take the data from your query, in this case the first 10 posts, and pass them to your callback function one by one. Your callback will have one parameter, the full object from the individual result. The callback is what you will use to do your actual processing. You will have full access to the query object here, so you can perform any actions you want. In this example, we will simply log the output.
`

Which implies posts_per_page set to 10 would only loop through 10 posts.
