### ISSUE TITLE
Add functionality to clear additional post meta fields that track individual batch process

### ISSUE THREAD

**Issue by zachwills** [reaktivstudios/locomotive#18]
Let's say you create a bunch of batch processes and run them. For each result that gets processed, a `post_meta` is added (for tracking) which could result in a ton of unnecessary database clog once the user runs that batch process for the last time. 

We need to add a way for users to clear out these additional database rows easily. Currently, if they 'reset' a batch, it will do this. Is this enough- or should we add a 'clear database' button that removes these but doesn't change the batch process status (resetting will change the status to 'reset').

**Comment by jjeaton** [comment]
@JasonHoffmann see related task here: https://github.com/reaktivstudios/locomotive/issues/53

**Comment by JasonHoffmann** [comment]
Ok, first step of this is #101
