### ISSUE TITLE
Fix major scrutinizer issues

### ISSUE THREAD

**Issue by jjeaton** [reaktivstudios/locomotive#29]

**Comment by JasonHoffmann** [comment]
I'm seeing two major issues come up in Scrutinizer. One is that it doesn't register WP_Post and WP_User as a registered class. Is there a best practice for introducing those classes from WordPress?

The other is that the $run variable is used multiple times in the same function to run batch processes. This can be solved by declaring the second $run as a different variable, but wanted to check.

**Comment by jjeaton** [comment]
We can ignore the class one. I believe it's b/c we don't have WordPress in
our repo so it can't find it. No big deal.

Fine with you fixing the $run variable in a new PR.
