### ISSUE TITLE
Add ability to set batch process description

### ISSUE THREAD

**Issue by zachwills** [reaktivstudios/locomotive#35]
The name of batch process shouldn't be too long, it would be nice to be able to set a description that could explain what the batch was intended to do.

I don't think it's necessary for the initial public release.

**Comment by jjeaton** [comment]
@JasonHoffmann @norcross thoughts on whether this is necessary/useful? I'm tempted to close this as wontfix.

**Comment by norcross** [comment]
I can see it being useful if this is set up for other users beyond the developer.

**Comment by JasonHoffmann** [comment]
Yea agreed. If this becomes a tool that developers set up for clients, it might be essential. Hard to tell now though.

**Comment by jjeaton** [comment]
In that case, let's close and we'll reopen if it becomes something we need.
