### ISSUE TITLE
Create a 'public ready' README

### ISSUE THREAD

**Issue by zachwills** [reaktivstudios/locomotive#43]
Can be basic, should probably just give an explanation of how to use the plugin and what to expect when you use it. Maybe link to the GitHub wiki.

**Comment by JasonHoffmann** [comment]
It's by no means exhaustive or complete, but I started things off here: https://github.com/reaktivstudios/locomotive/wiki

I know the API isn't completely worked out, but the sooner we start documenting the process the clearer I think it will be.

**Comment by zachwills** [comment]
Good start @JasonHoffmann! I like what you've added so far.

**Comment by jjeaton** [comment]
Great stuff, can you link to the wiki from the README?

**Comment by JasonHoffmann** [comment]
I’ve added an examples section to the README: https://github.com/reaktivstudios/locomotive/wiki/Examples

Hoping to put some common use cases there. We don’t have comment queries in here yet, so for now I put a reset password function.
