### ISSUE TITLE
Normalize register batch arguments

### ISSUE THREAD

**Issue by zachwills** [reaktivstudios/locomotive#61]
Right now, some of the batch query arguments vary depending on the type of batch you are running (since the underlying `query_vars` are named differently). 

I think we should come up with our own standard arguments that get passed when you register a batch, and handle converting those arguments to the batch-specific args within the batch class.

For approach, we could update the `abstract Batch` class to include an abstract function like `convert_args_to_query_vars()` that gets implemented on each individual batch class.

**Comment by JasonHoffmann** [comment]
This seems to be a bit of a blocker. We could start by normalizing the variable `per_batch` to `number` or `posts_per_page` and keep offset as another standard variable.

The function could be smart enough to accept the normalized variables AND query specific variables. So if you did happen to use a WP_Query argument, it would just overwrite the defaults, giving it some flexibility. This would most likely require iterating through some conditionals in each individual class, then parsing and merging args after this is complete.

**Comment by jjeaton** [comment]
I think @zachwills had some in progress work here. @zachwills do you plan on finishing this feature?

**Comment by zachwills** [comment]
@jjeaton I will push up something I was working on this morning that is semi-related to this. If I remember correctly, part of the goal behind this was to eliminate some of the repeated code within each batch types (Post and User)'s `get_results()` method.

It may be going in a direction we end up not liking, so I'd rather push it up now and get some feedback from the team about the direction so it can move in the right direction.

**Comment by zachwills** [comment]
After thinking through this some more I'm not quite sure that there is enough of a reason to normalize the args. We kind of handle the different pagination parameters with the `$per_batch_param` property introduced in #85.

Maybe we should brainstorm a list of what parameters are different across the different WP_* queries? I know in my example in the issue description I mentioned `posts_per_page` vs `number`.

Also, I kind of like keeping the amount of logic that the base class has to do down to a minimum. I think it will make maintaining and improving the plugin easier as more queries get introduced ( #42 ).

**Comment by JasonHoffmann** [comment]
Sure here's a first attempt. Using User, Post and Terms as reference

#### Include:
User (include) | Post (post__in) | Term (include)

#### Exclude
User (exclude) | Post (post__not_in) | Term (exclude)

#### Search
User (search) | Post (s) | Term (search)

#### Number
User (number) | Post (posts_per_page) | Term (number)

#### Parent
User (N/A) | Post (post_parent) | Term (parent)

Then of course WP_Meta_Query blows this all out of the water. Agreed that not sure normalizing is the best way to go, since everything is pretty distinct. But,
- Probably still makes sense to normalize number, can see that being an issue when more custom queries are introduced
- Doesn't hurt to add error checking to catch some of these. For instance, if a person types `search` instead of `s` in their WP_Post query, we can catch that, and switch it to the right variable.

**Comment by zachwills** [comment]
Thanks for coming up with that @JasonHoffmann.

Seeing the list, I suppose it would make sense to implement the ability for the classes to map a normalized parameter to it's query-specific equivalent. I'm not sure I'm sold on the error checking. I'd really like to try to keep the abstract class as minimal as possible.

For implementation, maybe we add a new property on the class like so (example for the `class-batch-posts.php` class):

```php
protected $mapped_query_args = array(
    // 'normalized_arg' => 'query_specific_arg',
    'per_batch'         => 'posts_per_page',
    'search'            => 's',
    'include'           => 'post__in',
);
```

Then we can implement a new function on the parent class like `process_query_args` or something that runs a conversion on the `$this->args` based on the `$this->mapped_query_args`. What do ya'll think of that?

**Comment by JasonHoffmann** [comment]
Yea that's more along the lines of what I was thinking. Keep the normalized parameters in the child classes. Originally I was thinking create an abstract function like `normalize_args` and then implement in each class, but this is way is even simpler.

**Comment by zachwills** [comment]
Cool- I'll try to get that into this PR then for review sometime during the week.

**Comment by jjeaton** [comment]
In support of the mapped query args approach. Basically I just want `posts_per_page` and `number` to work for any query, etc. Simple, nothing fancy. Let's get this in.

**Comment by zachwills** [comment]
@jjeaton I'm a little confused- you want both of those to work on any type of batch?

The goal of this issue (originally, at least) was to standardize some args across all of the queries. For example:

- `per_batch` vs `posts_per_page` or `number`
- `include` vs `post|site__in`
- `exclude` vs `post|site__not_in`
- etc.

Is that still the goal? If so, I can submit a PR with these (and whatever others I find) and from there we can swap out whichever parameter names we think are best. Once we get something merged, we can update the wiki (&/or the README) to list out the normalized params. Let me know what you think.

**Comment by jjeaton** [comment]
@zachwills I think I was confused. IIRC, I wasn't a fan of the `per_batch` naming, b/c it was too different from the normal WP params. 

And now I am again talking myself out of normalizing these at all. 😂  If my goal was to make it more familiar for WP devs, by adding new normalized parameters that are different we've just confused things more. Maybe this isn't worth it.

**Comment by zachwills** [comment]
Haha I was thinking the same thing earlier in the thread. Since we just pass the args through the users can just pass whatever they want. The flip side is that it is really easy to allow for a standardized approach, so that alone might make it worthwhile.

Maybe we leave it as is until we run into a use case where we wished there was a normalized set of params?

Sent from my iPhone

On Dec 13, 2016, at 10:08 AM, Josh Eaton <notifications@github.com<mailto:notifications@github.com>> wrote:


@zachwills<https://github.com/zachwills> I think I was confused. IIRC, I wasn't a fan of the per_batch naming, b/c it was too different from the normal WP params.

And now I am again talking myself out of normalizing these at all. ? If my goal was to make it more familiar for WP devs, by adding new normalized parameters that are different we've just confused things more. Maybe this isn't worth it.

-
