### ISSUE TITLE
default / built in batches

### ISSUE THREAD

**Issue by norcross** [reaktivstudios/locomotive#62]
possibly include some default batches (that can be disabled). things like deleting spam comments, post revisions, etc

**Comment by JasonHoffmann** [comment]
A good first step on this would be to have a “common use cases” section in the documentation that has some example functions. Do we have a list of processes we think would fit?

**Comment by jjeaton** [comment]
The primary use case for this has always been data migrations in environments where wp-cli is not available or inconvenient. So it is development-focused and for what are normally unique cases (reformat this post meta to new format, migrate these posts to a new post type, change these user's roles, delete this obsolete data)

That said, here are potentially a few common use cases:

* Reset passwords for all users
* Delete all spam comments
* Mark any unapproved comments as approved

**Comment by norcross** [comment]
the possible defaults listed here are also in the wiki documentation. perhaps we just point to that?

**Comment by jjeaton** [comment]
Agreed.
