### ISSUE TITLE
admin menu icon

### ISSUE THREAD

**Issue by norcross** [reaktivstudios/locomotive#77]
currently using the default gear icon. should get SVG icon.

possible icon to use: https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Train_Austria.svg/1000px-Train_Austria.svg.png

**Comment by norcross** [comment]
any thoughts / ideas on the icon?

**Comment by JasonHoffmann** [comment]
If we move this to the tools menu, it won't be necessary any longer.

**Comment by norcross** [comment]
agreed. I didn't know we were moving in that direction. 

although I'd argue we should still have some sort of icon / branding for it

**Comment by jjeaton** [comment]
See conversation here: https://github.com/reaktivstudios/locomotive/pull/99#issuecomment-271651351

**Comment by jjeaton** [comment]
For the project itself (and not the admin menu) I envision a steam locomotive, something like these creative commons options:

Favorite: https://thenounproject.com/term/locomotive/650905/
https://thenounproject.com/term/train/39857/
https://thenounproject.com/term/train/596432/
https://thenounproject.com/term/train/3890/
https://thenounproject.com/term/train/27483/
https://thenounproject.com/term/train/605979/
https://thenounproject.com/term/train/9595/

We just have to provide attribution to use.

**Comment by norcross** [comment]
I'm on board with the favorite

**Comment by JasonHoffmann** [comment]
Same here. Be nice to have a logo of some sort with it

**Comment by jjeaton** [comment]
Cool, let's get it added to the README...maybe the admin screen? Attribution can go in README and plugin header comment.

**Comment by jjeaton** [comment]
Closed in favor of submenu. Logo chosen for readme.
